use v6;
# generated by gen-properties.pl --role=CSS::Language::CSS1::_Interface etc/css1-properties.txt
role CSS::Language::CSS1::_Interface {
    method absolute-size($/) { ... }
    method family-name($/) { ... }
    method generic-family($/) { ... }
    method integer($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method url($/) { ... }
}
