#  -- DO NOT EDIT --
# generated by: compile-modules.raku
use NativeCall;
use CSS::Module::Property;

module CSS::Snapshot2026::Fonts::AtFontPaletteValues::Metadata {
    BEGIN our $property = ${:base-palette(${:default("N/A"), :inherit(Bool::False), :synopsis("light | dark | <integer [0,∞]>")}), :font-family(${:default("N/A"), :inherit(Bool::False), :synopsis("<font-family-name>#")}), :override-colors(${:default("N/A"), :inherit(Bool::False), :synopsis("[ <integer [0,∞]> <color> ]#")})};
    our enum prop-names <base-palette font-family override-colors>;
    our sub index {
        state $ //= do {
            my $enums := prop-names.enums;
            CArray[CSS::Module::Property].new: |$property.sort.map({CSS::Module::Property.new(:$enums, name => .key, |.value)});
        }
    }
}

