use v6;
# generated by gen-properties.pl --role=CSS::Language::CSS21::_Interface etc/css21-properties.txt
role CSS::Language::CSS21::_Interface {
    method absolute-size($/) { ... }
    method angle($/) { ... }
    method attr($/) { ... }
    method counter($/) { ... }
    method family-name($/) { ... }
    method frequency($/) { ... }
    method generic-family($/) { ... }
    method generic-voice($/) { ... }
    method identifier($/) { ... }
    method integer($/) { ... }
    method length($/) { ... }
    method margin-width($/) { ... }
    method number($/) { ... }
    method padding-width($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method shape($/) { ... }
    method specific-voice($/) { ... }
    method string($/) { ... }
    method time($/) { ... }
    method uri($/) { ... }
}
