use v6;
#  -- DO NOT EDIT --
# generated by css-gen-properties.pl --class=CSS::Module::CSS3::Fonts::Spec::Actions etc/css3x-font-properties.txt

class CSS::Module::CSS3::Fonts::Spec::Actions {

    #= font: [ [ <‘font-style’> || <font-variant-css21> || <‘font-weight’> || <‘font-stretch’> ]? <‘font-size’> [ / <‘line-height’> ]? <‘font-family’> ] | caption | icon | menu | message-box | small-caption | status-bar
    method decl:sym<font>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-family: [ <family-name> | <generic-family> ]#
    method decl:sym<font-family>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-family($/) { make $.list($/) }

    #= font-feature-settings: normal | <feature-tag-value>#
    method decl:sym<font-feature-settings>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-kerning: auto | normal | none
    method decl:sym<font-kerning>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-language-override: normal | <string>
    method decl:sym<font-language-override>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-size: <absolute-size> | <relative-size> | <length> | <percentage>
    method decl:sym<font-size>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-size($/) { make $.list($/) }

    #= font-size-adjust: none | auto | <number>
    method decl:sym<font-size-adjust>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-stretch: normal | ultra-condensed | extra-condensed | condensed | semi-condensed | semi-expanded | expanded | extra-expanded | ultra-expanded
    method decl:sym<font-stretch>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-stretch($/) { make $.list($/) }

    #= font-style: normal | italic | oblique
    method decl:sym<font-style>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-style($/) { make $.list($/) }

    #= font-synthesis: none | [ weight || style ]
    method decl:sym<font-synthesis>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-variant: normal | none | [ <common-lig-values> || <discretionary-lig-values> || <historical-lig-values> || <contextual-alt-values> || stylistic(<feature-value-name>) || historical-forms || styleset(<feature-value-name>#) || character-variant(<feature-value-name>#) || swash(<feature-value-name>) || ornaments(<feature-value-name>) || annotation(<feature-value-name>) || [ small-caps | all-small-caps | petite-caps | all-petite-caps | unicase | titling-caps ] || <numeric-figure-values> || <numeric-spacing-values> || <numeric-fraction-values> || ordinal || slashed-zero || <east-asian-variant-values> || <east-asian-width-values> || ruby ]#
    method decl:sym<font-variant>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-variant-alternates: normal | [ stylistic(<feature-value-name>) || historical-forms || styleset(<feature-value-name>#) || character-variant(<feature-value-name>#) || swash(<feature-value-name>) || ornaments(<feature-value-name>) || annotation(<feature-value-name>) ]
    method decl:sym<font-variant-alternates>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-variant-caps: normal | small-caps | all-small-caps | petite-caps | all-petite-caps | unicase | titling-caps
    method decl:sym<font-variant-caps>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-variant-east-asian: normal | [ <east-asian-variant-values> || <east-asian-width-values> || ruby ]
    method decl:sym<font-variant-east-asian>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-variant-ligatures: normal | none | [ <common-lig-values> || <discretionary-lig-values> || <historical-lig-values> || <contextual-alt-values> ]
    method decl:sym<font-variant-ligatures>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-variant-numeric: normal | [ <numeric-figure-values> || <numeric-spacing-values> || <numeric-fraction-values> || ordinal || slashed-zero ]
    method decl:sym<font-variant-numeric>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-variant-position: normal | sub | super
    method decl:sym<font-variant-position>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #= font-weight: normal | bold | bolder | lighter | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900
    method decl:sym<font-weight>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-weight($/) { make $.list($/) }

    #= line-height: normal | <number> | <length> | <percentage>
    method decl:sym<line-height>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-line-height($/) { make $.list($/) }
}
