use v6;
#  -- DO NOT EDIT --
# generated by: make_properties.pl 

class CSS::Module::CSS3::Fonts::Spec::Actions {
    method expr-font-family($/) { make $.list($/) }
    method expr-font-size($/) { make $.list($/) }
    method expr-font-stretch($/) { make $.list($/) }
    method expr-font-style($/) { make $.list($/) }
    method expr-font-weight($/) { make $.list($/) }
    method expr-line-height($/) { make $.list($/) }
}
