use v6;
#  -- DO NOT EDIT --
# generated by: Build.pm 
role CSS::Module::CSS3::Fonts::Spec::Interface {
    method absolute-size($/) { ... }
    method common-lig-values($/) { ... }
    method contextual-alt-values($/) { ... }
    method discretionary-lig-values($/) { ... }
    method east-asian-variant-values($/) { ... }
    method east-asian-width-values($/) { ... }
    method family-name($/) { ... }
    method feature-tag-value($/) { ... }
    method feature-value-name($/) { ... }
    method font-variant-css21($/) { ... }
    method generic-family($/) { ... }
    method historical-lig-values($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method numeric-figure-values($/) { ... }
    method numeric-fraction-values($/) { ... }
    method numeric-spacing-values($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method string($/) { ... }
}
