use v6;
#  -- DO NOT EDIT --
# generated by: Build.pm 

class CSS::Module::CSS1::Spec::Actions {

    #| font-family: [[<family-name> | <generic-family>],]* [<family-name> | <generic-family>]
    method decl:sym<font-family>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-family($/) { make $.list($/) }

    #| font-style: normal | italic | oblique
    method decl:sym<font-style>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-style($/) { make $.list($/) }

    #| font-variant: normal | small-caps
    method decl:sym<font-variant>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-variant($/) { make $.list($/) }

    #| font-weight: normal | bold | bolder | lighter | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900
    method decl:sym<font-weight>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-weight($/) { make $.list($/) }

    #| font-size: <absolute-size> | <relative-size> | <length> | <percentage>
    method decl:sym<font-size>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-font-size($/) { make $.list($/) }

    #| font: [ 'font-style' || 'font-variant' || 'font-weight' ]? 'font-size' [ / 'line-height' ]? 'font-family'
    method decl:sym<font>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| color: <color>
    method decl:sym<color>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| background-color: <color> | transparent
    method decl:sym<background-color>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-background-color($/) { make $.list($/) }

    #| background-image: <uri> | none
    method decl:sym<background-image>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-background-image($/) { make $.list($/) }

    #| background-repeat: repeat | repeat-x | repeat-y | no-repeat
    method decl:sym<background-repeat>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-background-repeat($/) { make $.list($/) }

    #| background-attachment: scroll | fixed
    method decl:sym<background-attachment>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-background-attachment($/) { make $.list($/) }

    #| background-position: [<percentage> | <length>]{1,2} | [top | center | bottom] || [left | center | right]
    method decl:sym<background-position>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-background-position($/) { make $.list($/) }

    #| background: 'background-color' || 'background-image' || 'background-repeat' || 'background-attachment' || 'background-position'
    method decl:sym<background>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| word-spacing: normal | <length>
    method decl:sym<word-spacing>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| letter-spacing: normal | <length>
    method decl:sym<letter-spacing>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| text-decoration: none | [ underline || overline || line-through || blink ]
    method decl:sym<text-decoration>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| vertical-align: baseline | sub | super | top | text-top | middle | bottom | text-bottom | <percentage>
    method decl:sym<vertical-align>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| text-transform: capitalize | uppercase | lowercase | none
    method decl:sym<text-transform>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| text-align: left | right | center | justify
    method decl:sym<text-align>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| text-indent: <length> | <percentage>
    method decl:sym<text-indent>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| line-height: normal | <number> | <length> | <percentage>
    method decl:sym<line-height>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-line-height($/) { make $.list($/) }

    #| margin-top: <length> | <percentage> | auto
    method decl:sym<margin-top>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| margin-right: <length> | <percentage> | auto
    method decl:sym<margin-right>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| margin-bottom: <length> | <percentage> | auto
    method decl:sym<margin-bottom>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| margin-left: <length> | <percentage> | auto
    method decl:sym<margin-left>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| margin: [ <length> | <percentage> | auto ]{1,4}
    method decl:sym<margin>($/) { make $.decl($/, &?ROUTINE.WHY, :boxed) }

    #| padding-top: <length> | <percentage>
    method decl:sym<padding-top>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| padding-right: <length> | <percentage>
    method decl:sym<padding-right>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| padding-bottom: <length> | <percentage>
    method decl:sym<padding-bottom>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| padding-left: <length> | <percentage>
    method decl:sym<padding-left>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| padding: [ <length> | <percentage> ]{1,4}
    method decl:sym<padding>($/) { make $.decl($/, &?ROUTINE.WHY, :boxed) }

    #| border-top-width: thin | medium | thick | <length>
    method decl:sym<border-top-width>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-border-top-width($/) { make $.list($/) }

    #| border-right-width: thin | medium | thick | <length>
    method decl:sym<border-right-width>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-border-right-width($/) { make $.list($/) }

    #| border-bottom-width: thin | medium | thick | <length>
    method decl:sym<border-bottom-width>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-border-bottom-width($/) { make $.list($/) }

    #| border-left-width: thin | medium | thick | <length>
    method decl:sym<border-left-width>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-border-left-width($/) { make $.list($/) }

    #| border-width: [thin | medium | thick | <length>]{1,4}
    method decl:sym<border-width>($/) { make $.decl($/, &?ROUTINE.WHY, :boxed) }
    method expr-border-width($/) { make $.list($/) }

    #| border-color: <color>{1,4}
    method decl:sym<border-color>($/) { make $.decl($/, &?ROUTINE.WHY, :boxed) }

    #| border-style: [ none | dotted | dashed | solid | double | groove | ridge | inset | outset ]{1,4}
    method decl:sym<border-style>($/) { make $.decl($/, &?ROUTINE.WHY, :boxed) }
    method expr-border-style($/) { make $.list($/) }

    #| border-top: 'border-top-width' || 'border-style' || <color>
    method decl:sym<border-top>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| border-right: 'border-right-width' || 'border-style' || <color>
    method decl:sym<border-right>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| border-bottom: 'border-bottom-width' || 'border-style' || <color>
    method decl:sym<border-bottom>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| border-left: 'border-left-width' || 'border-style' || <color>
    method decl:sym<border-left>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| border: 'border-width' || 'border-style' || <border-color>
    method decl:sym<border>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| width: <length> | <percentage> | auto
    method decl:sym<width>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| height: <length> | auto
    method decl:sym<height>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| float: left | right | none
    method decl:sym<float>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| clear: none | left | right | both
    method decl:sym<clear>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| display: block | inline | list-item | none
    method decl:sym<display>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| white-space: normal | pre | nowrap
    method decl:sym<white-space>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| list-style-type: disc | circle | square | decimal | lower-roman | upper-roman | lower-alpha | upper-alpha | none
    method decl:sym<list-style-type>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-list-style-type($/) { make $.list($/) }

    #| list-style-image: <uri> | none
    method decl:sym<list-style-image>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-list-style-image($/) { make $.list($/) }

    #| list-style-position: inside | outside
    method decl:sym<list-style-position>($/) { make $.decl($/, &?ROUTINE.WHY) }
    method expr-list-style-position($/) { make $.list($/) }

    #| list-style: 'list-style-type' || 'list-style-image' || 'list-style-position'
    method decl:sym<list-style>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| position: absolute | relative | static
    method decl:sym<position>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| left: <length> | <percentage> | auto
    method decl:sym<left>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| top: <length> | <percentage> | auto
    method decl:sym<top>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| overflow: none | clip | scroll
    method decl:sym<overflow>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| z-index: auto | <integer>
    method decl:sym<z-index>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| visibility: inherit | visible | hidden
    method decl:sym<visibility>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| page-break-before: auto | allways | left | right
    method decl:sym<page-break-before>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| page-break-after: auto | allways | left | right
    method decl:sym<page-break-after>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| size: <length>{1,2} | auto | portrait | landscape
    method decl:sym<size>($/) { make $.decl($/, &?ROUTINE.WHY) }

    #| marks: crop || cross | none
    method decl:sym<marks>($/) { make $.decl($/, &?ROUTINE.WHY) }
}
