use v6;
#  -- DO NOT EDIT --
# generated by css-gen-properties.pl --role=CSS::Module::CSS1::Spec::Interface etc/css1-properties.txt
role CSS::Module::CSS1::Spec::Interface {
    method absolute-size($/) { ... }
    method border-color($/) { ... }
    method color($/) { ... }
    method family-name($/) { ... }
    method generic-family($/) { ... }
    method integer($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method uri($/) { ... }
}
