use v6;
#  -- DO NOT EDIT --
# generated by: Build.pm 

class CSS::Module::CSS3::PagedMedia::Spec::Actions {

    #| size: <length>{1,2} | auto | [ <page-size> || [ portrait | landscape] ]
    method decl:sym<size>($/) { make $.decl($/, &?ROUTINE.WHY) }
}
