use v6;
#  -- DO NOT EDIT --
# generated by css-gen-properties.pl --role=CSS::Module::CSS3::PagedMedia::Spec::Interface etc/css3x-paged-media.txt
role CSS::Module::CSS3::PagedMedia::Spec::Interface {
    method length($/) { ... }
    method page-size($/) { ... }
}
