#  -- DO NOT EDIT --
# generated by: compile-modules.raku
use NativeCall;
use CSS::Module::Property;

module CSS::Snapshot2026::Fonts::AtFontFeatureValues::Metadata {
    BEGIN our $property = ${:font-display(${:default("auto"), :inherit(Bool::False), :synopsis("auto | block | swap | fallback | optional")})};
    our enum prop-names <font-display>;
    our sub index {
        state $ //= do {
            my $enums := prop-names.enums;
            CArray[CSS::Module::Property].new: |$property.sort.map({CSS::Module::Property.new(:$enums, name => .key, |.value)});
        }
    }
}

