use v6;
#  -- DO NOT EDIT --
# generated by: gen-properties.pl --grammar=CSS::Language::CSS3::PagedMedia::Spec::Grammar --proforma etc/css3x-paged-media.txt

grammar CSS::Language::CSS3::PagedMedia::Spec::Grammar {

    #= size: <length>{1,2} | auto | [ <page-size> || [ portrait | landscape] ]
    rule decl:sym<size> {:i (size) ':'  [ <proforma> || <expr=.expr-size> || <any-args> ] }
    rule expr-size {:i [ <length>**1..2 | auto & <keyw> | [ [:my @*SEEN; <page-size> <!seen(0)> | [ [ portrait | landscape ] & <keyw> ] <!seen(1)> ]+ ] ] }
}
