use v6;
# generated by gen-properties.pl --role=CSS::Language::CSS3::PagedMedia::Spec::Interface etc/css3x-paged-media.txt
role CSS::Language::CSS3::PagedMedia::Spec::Interface {
    method length($/) { ... }
    method page-size($/) { ... }
}
