use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 

class CSS::Module::CSS3::Fonts::AtFontFace::Spec::Actions {
    method family-name($/) { make $.node($/).pairs[0] }
    method font-face-name($/) { make $.node($/).pairs[0] }
}
