use v6;
#  -- DO NOT EDIT --
# generated by gen-properties.pl --role=CSS::Language::CSS3::Fonts::Spec::Interface etc/css3x-font-properties.txt
role CSS::Language::CSS3::Fonts::Spec::Interface {
    method absolute-size($/) { ... }
    method common-lig-values($/) { ... }
    method contextual-alt-values($/) { ... }
    method discretionary-lig-values($/) { ... }
    method east-asian-variant-values($/) { ... }
    method east-asian-width-values($/) { ... }
    method expr-font-family($/) { ... }
    method expr-font-size($/) { ... }
    method expr-font-stretch($/) { ... }
    method expr-font-style($/) { ... }
    method expr-font-weight($/) { ... }
    method expr-line-height($/) { ... }
    method family-name($/) { ... }
    method feature-tag-value($/) { ... }
    method feature-value-name($/) { ... }
    method font-variant-css21($/) { ... }
    method generic-family($/) { ... }
    method historical-lig-values($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method numeric-figure-values($/) { ... }
    method numeric-fraction-values($/) { ... }
    method numeric-spacing-values($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method string($/) { ... }
}
