use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 

class CSS::Module::CSS21::Spec::Actions {
    method expr-background-attachment($/) { make $.list($/) }
    method expr-background-color($/) { make $.list($/) }
    method expr-background-image($/) { make $.list($/) }
    method expr-background-position($/) { make $.list($/) }
    method expr-background-repeat($/) { make $.list($/) }
    method expr-border-color($/) { make $.list($/) }
    method expr-border-style($/) { make $.list($/) }
    method expr-border-width($/) { make $.list($/) }
    method expr-cue-after($/) { make $.list($/) }
    method expr-cue-before($/) { make $.list($/) }
    method expr-font-family($/) { make $.list($/) }
    method expr-font-size($/) { make $.list($/) }
    method expr-font-style($/) { make $.list($/) }
    method expr-font-variant($/) { make $.list($/) }
    method expr-font-weight($/) { make $.list($/) }
    method expr-line-height($/) { make $.list($/) }
    method expr-list-style-image($/) { make $.list($/) }
    method expr-list-style-position($/) { make $.list($/) }
    method expr-list-style-type($/) { make $.list($/) }
    method expr-outline-color($/) { make $.list($/) }
    method expr-outline-style($/) { make $.list($/) }
    method expr-outline-width($/) { make $.list($/) }
}
