use v6;
#  -- DO NOT EDIT --
# generated by: make_properties.pl 
role CSS::Module::CSS21::Spec::Interface {
    method absolute-size($/) { ... }
    method angle($/) { ... }
    method attr($/) { ... }
    method color($/) { ... }
    method counter($/) { ... }
    method counters($/) { ... }
    method family-name($/) { ... }
    method frequency($/) { ... }
    method generic-family($/) { ... }
    method generic-voice($/) { ... }
    method identifier($/) { ... }
    method integer($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method shape($/) { ... }
    method specific-voice($/) { ... }
    method string($/) { ... }
    method time($/) { ... }
    method uri($/) { ... }
}
