use v6;
#  -- DO NOT EDIT --
# generated by css-gen-properties.pl --role=CSS::Language::CSS3::Fonts::AtFontFace::Spec::Interface etc/css3x-font-@fontface-properties.txt
role CSS::Language::CSS3::Fonts::AtFontFace::Spec::Interface {
    method common-lig-values($/) { ... }
    method contextual-alt-values($/) { ... }
    method discretionary-lig-values($/) { ... }
    method east-asian-variant-values($/) { ... }
    method east-asian-width-values($/) { ... }
    method family-name($/) { ... }
    method feature-tag-value($/) { ... }
    method feature-value-name($/) { ... }
    method font-face-name($/) { ... }
    method historical-lig-values($/) { ... }
    method numeric-figure-values($/) { ... }
    method numeric-fraction-values($/) { ... }
    method numeric-spacing-values($/) { ... }
    method string($/) { ... }
    method urange($/) { ... }
    method uri($/) { ... }
}
