use v6;
#  -- DO NOT EDIT --
# generated by gen-properties.pl --role=CSS::Language::CSS1::Spec::Interface etc/css1-properties.txt
role CSS::Language::CSS1::Spec::Interface {
    method absolute-size($/) { ... }
    method expr-background-attachment($/) { ... }
    method expr-background-color($/) { ... }
    method expr-background-image($/) { ... }
    method expr-background-position($/) { ... }
    method expr-background-repeat($/) { ... }
    method expr-border-bottom-width($/) { ... }
    method expr-border-left-width($/) { ... }
    method expr-border-right-width($/) { ... }
    method expr-border-style($/) { ... }
    method expr-border-top-width($/) { ... }
    method expr-border-width($/) { ... }
    method expr-font-family($/) { ... }
    method expr-font-size($/) { ... }
    method expr-font-style($/) { ... }
    method expr-font-variant($/) { ... }
    method expr-font-weight($/) { ... }
    method expr-line-height($/) { ... }
    method expr-list-style-image($/) { ... }
    method expr-list-style-position($/) { ... }
    method expr-list-style-type($/) { ... }
    method family-name($/) { ... }
    method generic-family($/) { ... }
    method integer($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method uri($/) { ... }
}
