#  -- DO NOT EDIT --
# generated by: compile-modules.raku
use NativeCall;
use CSS::Module::Property;

module CSS::Snapshot2026::Color::AtColorProfile::Metadata {
    BEGIN our $property = ${:components(${:default("n/a"), :inherit(Bool::False), :synopsis("<ident>#")}), :rendering-intent(${:default("relative-colorimetric"), :inherit(Bool::False), :synopsis("relative-colorimetric | absolute-colorimetric | perceptual | saturation")}), :src(${:default("n/a"), :inherit(Bool::False), :synopsis("<url>")})};
    our enum prop-names <components rendering-intent src>;
    our sub index {
        state $ //= do {
            my $enums := prop-names.enums;
            CArray[CSS::Module::Property].new: |$property.sort.map({CSS::Module::Property.new(:$enums, name => .key, |.value)});
        }
    }
}

