use v6;
#  -- DO NOT EDIT --
# generated by: gen-properties.pl --grammar=CSS::Language::CSS21::Spec::Grammar --proforma etc/css21-properties.txt

grammar CSS::Language::CSS21::Spec::Grammar {

    #= azimuth: <angle> | [[ left-side | far-left | left | center-left | center | center-right | right | far-right | right-side ] || behind ] | leftwards | rightwards
    rule decl:sym<azimuth> {:i (azimuth) ':'  [ <proforma> || <expr=.expr-azimuth> || <any-args> ] }
    rule expr-azimuth {:i [ <angle> | [ [:my @*SEEN; [ [ left\-side | far\-left | left | center\-left | center | center\-right | right | far\-right | right\-side ] & <keyw> ] <!seen(0)> | behind & <keyw> <!seen(1)> ]+ ] | [ leftwards | rightwards ] & <keyw> ] }

    #= background-attachment: scroll | fixed
    rule decl:sym<background-attachment> {:i (background\-attachment) ':'  [ <proforma> || <expr=.expr-background-attachment> || <any-args> ] }
    rule expr-background-attachment {:i [ scroll | fixed ] & <keyw> }

    #= background-color: <color> | transparent
    rule decl:sym<background-color> {:i (background\-color) ':'  [ <proforma> || <expr=.expr-background-color> || <any-args> ] }
    rule expr-background-color {:i [ <color> | transparent & <keyw> ] }

    #= background-image: <uri> | none
    rule decl:sym<background-image> {:i (background\-image) ':'  [ <proforma> || <expr=.expr-background-image> || <any-args> ] }
    rule expr-background-image {:i [ <uri> | none & <keyw> ] }

    #= background-position: [ [ <percentage> | <length> | left | center | right ] [ <percentage> | <length> | top | center | bottom ]? ] | [ [ left | center | right ] || [ top | center | bottom ] ]
    rule decl:sym<background-position> {:i (background\-position) ':'  [ <proforma> || <expr=.expr-background-position> || <any-args> ] }
    rule expr-background-position {:i [ [ [ [ <percentage> | <length> | [ left | center | right ] & <keyw> ] ] [ [ <percentage> | <length> | [ top | center | bottom ] & <keyw> ] ]? ] | [ [:my @*SEEN; [ [ left | center | right ] & <keyw> ] <!seen(0)> | [ [ top | center | bottom ] & <keyw> ] <!seen(1)> ]+ ] ] }

    #= background-repeat: repeat | repeat-x | repeat-y | no-repeat
    rule decl:sym<background-repeat> {:i (background\-repeat) ':'  [ <proforma> || <expr=.expr-background-repeat> || <any-args> ] }
    rule expr-background-repeat {:i [ repeat | repeat\-x | repeat\-y | no\-repeat ] & <keyw> }

    #= background: ['background-color' || 'background-image' || 'background-repeat' || 'background-attachment' || 'background-position']
    rule decl:sym<background> {:i (background) ':'  [ <proforma> || <expr=.expr-background> || <any-args> ] }
    rule expr-background {:i [ [:my @*SEEN; <expr-background-color> <!seen(0)> | <expr-background-image> <!seen(1)> | <expr-background-repeat> <!seen(2)> | <expr-background-attachment> <!seen(3)> | <expr-background-position> <!seen(4)> ]+ ] }

    #= border-collapse: collapse | separate
    rule decl:sym<border-collapse> {:i (border\-collapse) ':'  [ <proforma> || <expr=.expr-border-collapse> || <any-args> ] }
    rule expr-border-collapse {:i [ collapse | separate ] & <keyw> }

    #= border-color: [ <color> | transparent ]{1,4}
    rule decl:sym<border-color> {:i (border\-color) ':'  [ <proforma> || <expr=.expr-border-color>**1..4 || <any-args> ] }
    rule expr-border-color {:i [ [ <color> | transparent & <keyw> ] ] }

    #= border-spacing: <length> <length>?
    rule decl:sym<border-spacing> {:i (border\-spacing) ':'  [ <proforma> || <expr=.expr-border-spacing> || <any-args> ] }
    rule expr-border-spacing {:i <length> <length>? }

    #= border-style: [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ]{1,4}
    rule decl:sym<border-style> {:i (border\-style) ':'  [ <proforma> || <expr=.expr-border-style>**1..4 || <any-args> ] }
    rule expr-border-style {:i [ [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ] & <keyw> ] }

    #= border-top: [ 'border-width' || 'border-style' || 'border-color' ]
    rule decl:sym<border-top> {:i (border\-top) ':'  [ <proforma> || <expr=.expr-border-top> || <any-args> ] }
    rule expr-border-top {:i [ [:my @*SEEN; <expr-border-width> <!seen(0)> | <expr-border-style> <!seen(1)> | <expr-border-color> <!seen(2)> ]+ ] }

    #= border-right: [ 'border-width' || 'border-style' || 'border-color' ]
    rule decl:sym<border-right> {:i (border\-right) ':'  [ <proforma> || <expr=.expr-border-right> || <any-args> ] }
    rule expr-border-right {:i [ [:my @*SEEN; <expr-border-width> <!seen(0)> | <expr-border-style> <!seen(1)> | <expr-border-color> <!seen(2)> ]+ ] }

    #= border-bottom: [ 'border-width' || 'border-style' || 'border-color' ]
    rule decl:sym<border-bottom> {:i (border\-bottom) ':'  [ <proforma> || <expr=.expr-border-bottom> || <any-args> ] }
    rule expr-border-bottom {:i [ [:my @*SEEN; <expr-border-width> <!seen(0)> | <expr-border-style> <!seen(1)> | <expr-border-color> <!seen(2)> ]+ ] }

    #= border-left: [ 'border-width' || 'border-style' || 'border-color' ]
    rule decl:sym<border-left> {:i (border\-left) ':'  [ <proforma> || <expr=.expr-border-left> || <any-args> ] }
    rule expr-border-left {:i [ [:my @*SEEN; <expr-border-width> <!seen(0)> | <expr-border-style> <!seen(1)> | <expr-border-color> <!seen(2)> ]+ ] }

    #= border-top-color: <color> | transparent
    rule decl:sym<border-top-color> {:i (border\-top\-color) ':'  [ <proforma> || <expr=.expr-border-top-color> || <any-args> ] }
    rule expr-border-top-color {:i [ <color> | transparent & <keyw> ] }

    #= border-right-color: <color> | transparent
    rule decl:sym<border-right-color> {:i (border\-right\-color) ':'  [ <proforma> || <expr=.expr-border-right-color> || <any-args> ] }
    rule expr-border-right-color {:i [ <color> | transparent & <keyw> ] }

    #= border-bottom-color: <color> | transparent
    rule decl:sym<border-bottom-color> {:i (border\-bottom\-color) ':'  [ <proforma> || <expr=.expr-border-bottom-color> || <any-args> ] }
    rule expr-border-bottom-color {:i [ <color> | transparent & <keyw> ] }

    #= border-left-color: <color> | transparent
    rule decl:sym<border-left-color> {:i (border\-left\-color) ':'  [ <proforma> || <expr=.expr-border-left-color> || <any-args> ] }
    rule expr-border-left-color {:i [ <color> | transparent & <keyw> ] }

    #= border-top-style: [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ]
    rule decl:sym<border-top-style> {:i (border\-top\-style) ':'  [ <proforma> || <expr=.expr-border-top-style> || <any-args> ] }
    rule expr-border-top-style {:i [ [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ] & <keyw> ] }

    #= border-right-style: [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ]
    rule decl:sym<border-right-style> {:i (border\-right\-style) ':'  [ <proforma> || <expr=.expr-border-right-style> || <any-args> ] }
    rule expr-border-right-style {:i [ [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ] & <keyw> ] }

    #= border-bottom-style: [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ]
    rule decl:sym<border-bottom-style> {:i (border\-bottom\-style) ':'  [ <proforma> || <expr=.expr-border-bottom-style> || <any-args> ] }
    rule expr-border-bottom-style {:i [ [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ] & <keyw> ] }

    #= border-left-style: [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ]
    rule decl:sym<border-left-style> {:i (border\-left\-style) ':'  [ <proforma> || <expr=.expr-border-left-style> || <any-args> ] }
    rule expr-border-left-style {:i [ [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ] & <keyw> ] }

    #= border-top-width: thin | medium | thick | <length>
    rule decl:sym<border-top-width> {:i (border\-top\-width) ':'  [ <proforma> || <expr=.expr-border-top-width> || <any-args> ] }
    rule expr-border-top-width {:i [ [ thin | medium | thick ] & <keyw> | <length> ] }

    #= border-right-width: thin | medium | thick | <length>
    rule decl:sym<border-right-width> {:i (border\-right\-width) ':'  [ <proforma> || <expr=.expr-border-right-width> || <any-args> ] }
    rule expr-border-right-width {:i [ [ thin | medium | thick ] & <keyw> | <length> ] }

    #= border-bottom-width: thin | medium | thick | <length>
    rule decl:sym<border-bottom-width> {:i (border\-bottom\-width) ':'  [ <proforma> || <expr=.expr-border-bottom-width> || <any-args> ] }
    rule expr-border-bottom-width {:i [ [ thin | medium | thick ] & <keyw> | <length> ] }

    #= border-left-width: thin | medium | thick | <length>
    rule decl:sym<border-left-width> {:i (border\-left\-width) ':'  [ <proforma> || <expr=.expr-border-left-width> || <any-args> ] }
    rule expr-border-left-width {:i [ [ thin | medium | thick ] & <keyw> | <length> ] }

    #= border-width: thin | medium | thick | <length>{1,4}
    rule decl:sym<border-width> {:i (border\-width) ':'  [ <proforma> || <expr=.expr-border-width>**1..4 || <any-args> ] }
    rule expr-border-width {:i [ [ thin | medium | thick ] & <keyw> | <length>**1..4 ] }

    #= border: [ 'border-width' || 'border-style' || 'border-color' ]
    rule decl:sym<border> {:i (border) ':'  [ <proforma> || <expr=.expr-border> || <any-args> ] }
    rule expr-border {:i [ [:my @*SEEN; <expr-border-width> <!seen(0)> | <expr-border-style> <!seen(1)> | <expr-border-color> <!seen(2)> ]+ ] }

    #= bottom: <length> | <percentage> | auto
    rule decl:sym<bottom> {:i (bottom) ':'  [ <proforma> || <expr=.expr-bottom> || <any-args> ] }
    rule expr-bottom {:i [ <length> | <percentage> | auto & <keyw> ] }

    #= caption-side: top | bottom
    rule decl:sym<caption-side> {:i (caption\-side) ':'  [ <proforma> || <expr=.expr-caption-side> || <any-args> ] }
    rule expr-caption-side {:i [ top | bottom ] & <keyw> }

    #= clear: none | left | right | both
    rule decl:sym<clear> {:i (clear) ':'  [ <proforma> || <expr=.expr-clear> || <any-args> ] }
    rule expr-clear {:i [ none | left | right | both ] & <keyw> }

    #= clip: <shape> | auto
    rule decl:sym<clip> {:i (clip) ':'  [ <proforma> || <expr=.expr-clip> || <any-args> ] }
    rule expr-clip {:i [ <shape> | auto & <keyw> ] }

    #= color: <color>
    rule decl:sym<color> {:i (color) ':'  [ <proforma> || <expr=.expr-color> || <any-args> ] }
    rule expr-color {:i <color> }

    #= content: normal | none | [ <string> | <uri> | <counter> | <counters> | attr(<identifier>) | open-quote | close-quote | no-open-quote | no-close-quote ]+
    rule decl:sym<content> {:i (content) ':'  [ <proforma> || <expr=.expr-content> || <any-args> ] }
    rule expr-content {:i [ [ normal | none ] & <keyw> | [ [ <string> | <uri> | <counter> | <counters> | <attr> | [ open\-quote | close\-quote | no\-open\-quote | no\-close\-quote ] & <keyw> ] ]+ ] }

    #= counter-increment: [ <identifier> <integer>? ]+ | none
    rule decl:sym<counter-increment> {:i (counter\-increment) ':'  [ <proforma> || <expr=.expr-counter-increment> || <any-args> ] }
    rule expr-counter-increment {:i [ [ <identifier> <integer>? ]+ | none & <keyw> ] }

    #= counter-reset: [ <identifier> <integer>? ]+ | none
    rule decl:sym<counter-reset> {:i (counter\-reset) ':'  [ <proforma> || <expr=.expr-counter-reset> || <any-args> ] }
    rule expr-counter-reset {:i [ [ <identifier> <integer>? ]+ | none & <keyw> ] }

    #= cue-after: <uri> | none
    rule decl:sym<cue-after> {:i (cue\-after) ':'  [ <proforma> || <expr=.expr-cue-after> || <any-args> ] }
    rule expr-cue-after {:i [ <uri> | none & <keyw> ] }

    #= cue-before: <uri> | none
    rule decl:sym<cue-before> {:i (cue\-before) ':'  [ <proforma> || <expr=.expr-cue-before> || <any-args> ] }
    rule expr-cue-before {:i [ <uri> | none & <keyw> ] }

    #= cue: [ 'cue-before' || 'cue-after' ]
    rule decl:sym<cue> {:i (cue) ':'  [ <proforma> || <expr=.expr-cue> || <any-args> ] }
    rule expr-cue {:i [ [:my @*SEEN; <expr-cue-before> <!seen(0)> | <expr-cue-after> <!seen(1)> ]+ ] }

    #= cursor: [ [<uri> ,]* [ auto | crosshair | default | pointer | move | e-resize | ne-resize | nw-resize | n-resize | se-resize | sw-resize | s-resize | w-resize | text | wait | help | progress ] ]
    rule decl:sym<cursor> {:i (cursor) ':'  [ <proforma> || <expr=.expr-cursor> || <any-args> ] }
    rule expr-cursor {:i [ [ <uri> ',' ]* [ [ auto | crosshair | default | pointer | move | e\-resize | ne\-resize | nw\-resize | n\-resize | se\-resize | sw\-resize | s\-resize | w\-resize | text | wait | help | progress ] & <keyw> ] ] }

    #= direction: ltr | rtl
    rule decl:sym<direction> {:i (direction) ':'  [ <proforma> || <expr=.expr-direction> || <any-args> ] }
    rule expr-direction {:i [ ltr | rtl ] & <keyw> }

    #= display: inline | block | list-item | inline-block | table | inline-table | table-row-group | table-header-group | table-footer-group | table-row | table-column-group | table-column | table-cell | table-caption | none
    rule decl:sym<display> {:i (display) ':'  [ <proforma> || <expr=.expr-display> || <any-args> ] }
    rule expr-display {:i [ inline | block | list\-item | inline\-block | table | inline\-table | table\-row\-group | table\-header\-group | table\-footer\-group | table\-row | table\-column\-group | table\-column | table\-cell | table\-caption | none ] & <keyw> }

    #= elevation: <angle> | below | level | above | higher | lower
    rule decl:sym<elevation> {:i (elevation) ':'  [ <proforma> || <expr=.expr-elevation> || <any-args> ] }
    rule expr-elevation {:i [ <angle> | [ below | level | above | higher | lower ] & <keyw> ] }

    #= empty-cells: show | hide
    rule decl:sym<empty-cells> {:i (empty\-cells) ':'  [ <proforma> || <expr=.expr-empty-cells> || <any-args> ] }
    rule expr-empty-cells {:i [ show | hide ] & <keyw> }

    #= float: left | right | none
    rule decl:sym<float> {:i (float) ':'  [ <proforma> || <expr=.expr-float> || <any-args> ] }
    rule expr-float {:i [ left | right | none ] & <keyw> }

    #= font-family: [[ <family-name> | <generic-family> ] [, <family-name> | <generic-family> ]* ]
    rule decl:sym<font-family> {:i (font\-family) ':'  [ <proforma> || <expr=.expr-font-family> || <any-args> ] }
    rule expr-font-family {:i [ [ [ <family-name> | <generic-family> ] ] [ [ ',' <family-name> | <generic-family> ] ]* ] }

    #= font-size: <absolute-size> | <relative-size> | <length> | <percentage>
    rule decl:sym<font-size> {:i (font\-size) ':'  [ <proforma> || <expr=.expr-font-size> || <any-args> ] }
    rule expr-font-size {:i [ <absolute-size> | <relative-size> | <length> | <percentage> ] }

    #= font-style: normal | italic | oblique
    rule decl:sym<font-style> {:i (font\-style) ':'  [ <proforma> || <expr=.expr-font-style> || <any-args> ] }
    rule expr-font-style {:i [ normal | italic | oblique ] & <keyw> }

    #= font-variant: normal | small-caps
    rule decl:sym<font-variant> {:i (font\-variant) ':'  [ <proforma> || <expr=.expr-font-variant> || <any-args> ] }
    rule expr-font-variant {:i [ normal | small\-caps ] & <keyw> }

    #= font-weight: normal | bold | bolder | lighter | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900
    rule decl:sym<font-weight> {:i (font\-weight) ':'  [ <proforma> || <expr=.expr-font-weight> || <any-args> ] }
    rule expr-font-weight {:i [ [ normal | bold | bolder | lighter ] & <keyw> | [ 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 ] & <number> ] }

    #= font: [ [ 'font-style' || 'font-variant' || 'font-weight' ]? 'font-size' [ / 'line-height' ]? 'font-family' ] | caption | icon | menu | message-box | small-caption | status-bar
    rule decl:sym<font> {:i (font) ':'  [ <proforma> || <expr=.expr-font> || <any-args> ] }
    rule expr-font {:i [ [ [ [:my @*SEEN; <expr-font-style> <!seen(0)> | <expr-font-variant> <!seen(1)> | <expr-font-weight> <!seen(2)> ]+ ]? <expr-font-size> [ '/' <expr-line-height> ]? <expr-font-family> ] | [ caption | icon | menu | message\-box | small\-caption | status\-bar ] & <keyw> ] }

    #= height: <length> | <percentage> | auto
    rule decl:sym<height> {:i (height) ':'  [ <proforma> || <expr=.expr-height> || <any-args> ] }
    rule expr-height {:i [ <length> | <percentage> | auto & <keyw> ] }

    #= left: <length> | <percentage> | auto
    rule decl:sym<left> {:i (left) ':'  [ <proforma> || <expr=.expr-left> || <any-args> ] }
    rule expr-left {:i [ <length> | <percentage> | auto & <keyw> ] }

    #= letter-spacing: normal | <length>
    rule decl:sym<letter-spacing> {:i (letter\-spacing) ':'  [ <proforma> || <expr=.expr-letter-spacing> || <any-args> ] }
    rule expr-letter-spacing {:i [ normal & <keyw> | <length> ] }

    #= line-height: normal | <number> | <length> | <percentage>
    rule decl:sym<line-height> {:i (line\-height) ':'  [ <proforma> || <expr=.expr-line-height> || <any-args> ] }
    rule expr-line-height {:i [ normal & <keyw> | <number> | <length> | <percentage> ] }

    #= list-style-image: <uri> | none
    rule decl:sym<list-style-image> {:i (list\-style\-image) ':'  [ <proforma> || <expr=.expr-list-style-image> || <any-args> ] }
    rule expr-list-style-image {:i [ <uri> | none & <keyw> ] }

    #= list-style-position: inside | outside
    rule decl:sym<list-style-position> {:i (list\-style\-position) ':'  [ <proforma> || <expr=.expr-list-style-position> || <any-args> ] }
    rule expr-list-style-position {:i [ inside | outside ] & <keyw> }

    #= list-style-type: disc | circle | square | decimal | decimal-leading-zero | lower-roman | upper-roman | lower-greek | lower-latin | upper-latin | armenian | georgian | lower-alpha | upper-alpha | none
    rule decl:sym<list-style-type> {:i (list\-style\-type) ':'  [ <proforma> || <expr=.expr-list-style-type> || <any-args> ] }
    rule expr-list-style-type {:i [ disc | circle | square | decimal | decimal\-leading\-zero | lower\-roman | upper\-roman | lower\-greek | lower\-latin | upper\-latin | armenian | georgian | lower\-alpha | upper\-alpha | none ] & <keyw> }

    #= list-style: [ 'list-style-type' || 'list-style-position' || 'list-style-image' ]
    rule decl:sym<list-style> {:i (list\-style) ':'  [ <proforma> || <expr=.expr-list-style> || <any-args> ] }
    rule expr-list-style {:i [ [:my @*SEEN; <expr-list-style-type> <!seen(0)> | <expr-list-style-position> <!seen(1)> | <expr-list-style-image> <!seen(2)> ]+ ] }

    #= margin-right: <length> | <percentage>
    rule decl:sym<margin-right> {:i (margin\-right) ':'  [ <proforma> || <expr=.expr-margin-right> || <any-args> ] }
    rule expr-margin-right {:i [ <length> | <percentage> ] }

    #= margin-left: <length> | <percentage>
    rule decl:sym<margin-left> {:i (margin\-left) ':'  [ <proforma> || <expr=.expr-margin-left> || <any-args> ] }
    rule expr-margin-left {:i [ <length> | <percentage> ] }

    #= margin-top: <length> | <percentage>
    rule decl:sym<margin-top> {:i (margin\-top) ':'  [ <proforma> || <expr=.expr-margin-top> || <any-args> ] }
    rule expr-margin-top {:i [ <length> | <percentage> ] }

    #= margin-bottom: <length> | <percentage>
    rule decl:sym<margin-bottom> {:i (margin\-bottom) ':'  [ <proforma> || <expr=.expr-margin-bottom> || <any-args> ] }
    rule expr-margin-bottom {:i [ <length> | <percentage> ] }

    #= margin: [<length> | <percentage>]{1,4}
    rule decl:sym<margin> {:i (margin) ':'  [ <proforma> || <expr=.expr-margin>**1..4 || <any-args> ] }
    rule expr-margin {:i [ [ <length> | <percentage> ] ] }

    #= max-height: <length> | <percentage> | none
    rule decl:sym<max-height> {:i (max\-height) ':'  [ <proforma> || <expr=.expr-max-height> || <any-args> ] }
    rule expr-max-height {:i [ <length> | <percentage> | none & <keyw> ] }

    #= max-width: <length> | <percentage> | none
    rule decl:sym<max-width> {:i (max\-width) ':'  [ <proforma> || <expr=.expr-max-width> || <any-args> ] }
    rule expr-max-width {:i [ <length> | <percentage> | none & <keyw> ] }

    #= min-height: <length> | <percentage>
    rule decl:sym<min-height> {:i (min\-height) ':'  [ <proforma> || <expr=.expr-min-height> || <any-args> ] }
    rule expr-min-height {:i [ <length> | <percentage> ] }

    #= min-width: <length> | <percentage>
    rule decl:sym<min-width> {:i (min\-width) ':'  [ <proforma> || <expr=.expr-min-width> || <any-args> ] }
    rule expr-min-width {:i [ <length> | <percentage> ] }

    #= opacity: <number>
    rule decl:sym<opacity> {:i (opacity) ':'  [ <proforma> || <expr=.expr-opacity> || <any-args> ] }
    rule expr-opacity {:i <number> }

    #= orphans: <integer>
    rule decl:sym<orphans> {:i (orphans) ':'  [ <proforma> || <expr=.expr-orphans> || <any-args> ] }
    rule expr-orphans {:i <integer> }

    #= outline-color: <color> | invert
    rule decl:sym<outline-color> {:i (outline\-color) ':'  [ <proforma> || <expr=.expr-outline-color> || <any-args> ] }
    rule expr-outline-color {:i [ <color> | invert & <keyw> ] }

    #= outline-style: [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ]
    rule decl:sym<outline-style> {:i (outline\-style) ':'  [ <proforma> || <expr=.expr-outline-style> || <any-args> ] }
    rule expr-outline-style {:i [ [ none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset ] & <keyw> ] }

    #= outline-width: thin | medium | thick | <length>
    rule decl:sym<outline-width> {:i (outline\-width) ':'  [ <proforma> || <expr=.expr-outline-width> || <any-args> ] }
    rule expr-outline-width {:i [ [ thin | medium | thick ] & <keyw> | <length> ] }

    #= outline: [ 'outline-color' || 'outline-style' || 'outline-width' ]
    rule decl:sym<outline> {:i (outline) ':'  [ <proforma> || <expr=.expr-outline> || <any-args> ] }
    rule expr-outline {:i [ [:my @*SEEN; <expr-outline-color> <!seen(0)> | <expr-outline-style> <!seen(1)> | <expr-outline-width> <!seen(2)> ]+ ] }

    #= overflow: visible | hidden | scroll | auto
    rule decl:sym<overflow> {:i (overflow) ':'  [ <proforma> || <expr=.expr-overflow> || <any-args> ] }
    rule expr-overflow {:i [ visible | hidden | scroll | auto ] & <keyw> }

    #= padding-top: <length> | <percentage>
    rule decl:sym<padding-top> {:i (padding\-top) ':'  [ <proforma> || <expr=.expr-padding-top> || <any-args> ] }
    rule expr-padding-top {:i [ <length> | <percentage> ] }

    #= padding-right: <length> | <percentage>
    rule decl:sym<padding-right> {:i (padding\-right) ':'  [ <proforma> || <expr=.expr-padding-right> || <any-args> ] }
    rule expr-padding-right {:i [ <length> | <percentage> ] }

    #= padding-bottom: <length> | <percentage>
    rule decl:sym<padding-bottom> {:i (padding\-bottom) ':'  [ <proforma> || <expr=.expr-padding-bottom> || <any-args> ] }
    rule expr-padding-bottom {:i [ <length> | <percentage> ] }

    #= padding-left: <length> | <percentage>
    rule decl:sym<padding-left> {:i (padding\-left) ':'  [ <proforma> || <expr=.expr-padding-left> || <any-args> ] }
    rule expr-padding-left {:i [ <length> | <percentage> ] }

    #= padding: [<length> | <percentage>]{1,4}
    rule decl:sym<padding> {:i (padding) ':'  [ <proforma> || <expr=.expr-padding>**1..4 || <any-args> ] }
    rule expr-padding {:i [ [ <length> | <percentage> ] ] }

    #= page-break-after: auto | always | avoid | left | right
    rule decl:sym<page-break-after> {:i (page\-break\-after) ':'  [ <proforma> || <expr=.expr-page-break-after> || <any-args> ] }
    rule expr-page-break-after {:i [ auto | always | avoid | left | right ] & <keyw> }

    #= page-break-before: auto | always | avoid | left | right
    rule decl:sym<page-break-before> {:i (page\-break\-before) ':'  [ <proforma> || <expr=.expr-page-break-before> || <any-args> ] }
    rule expr-page-break-before {:i [ auto | always | avoid | left | right ] & <keyw> }

    #= page-break-inside: avoid | auto
    rule decl:sym<page-break-inside> {:i (page\-break\-inside) ':'  [ <proforma> || <expr=.expr-page-break-inside> || <any-args> ] }
    rule expr-page-break-inside {:i [ avoid | auto ] & <keyw> }

    #= pause-after: <time> | <percentage>
    rule decl:sym<pause-after> {:i (pause\-after) ':'  [ <proforma> || <expr=.expr-pause-after> || <any-args> ] }
    rule expr-pause-after {:i [ <time> | <percentage> ] }

    #= pause-before: <time> | <percentage>
    rule decl:sym<pause-before> {:i (pause\-before) ':'  [ <proforma> || <expr=.expr-pause-before> || <any-args> ] }
    rule expr-pause-before {:i [ <time> | <percentage> ] }

    #= pause: [ [<time> | <percentage>]{1,2} ]
    rule decl:sym<pause> {:i (pause) ':'  [ <proforma> || <expr=.expr-pause> || <any-args> ] }
    rule expr-pause {:i [ [ [ <time> | <percentage> ] ]**1..2 ] }

    #= pitch-range: <number>
    rule decl:sym<pitch-range> {:i (pitch\-range) ':'  [ <proforma> || <expr=.expr-pitch-range> || <any-args> ] }
    rule expr-pitch-range {:i <number> }

    #= pitch: <frequency> | x-low | low | medium | high | x-high
    rule decl:sym<pitch> {:i (pitch) ':'  [ <proforma> || <expr=.expr-pitch> || <any-args> ] }
    rule expr-pitch {:i [ <frequency> | [ x\-low | low | medium | high | x\-high ] & <keyw> ] }

    #= play-during: <uri> [ mix || repeat ]? | auto | none
    rule decl:sym<play-during> {:i (play\-during) ':'  [ <proforma> || <expr=.expr-play-during> || <any-args> ] }
    rule expr-play-during {:i [ <uri> [ [:my @*SEEN; mix & <keyw> <!seen(0)> | repeat & <keyw> <!seen(1)> ]+ ]? | [ auto | none ] & <keyw> ] }

    #= position: static | relative | absolute | fixed
    rule decl:sym<position> {:i (position) ':'  [ <proforma> || <expr=.expr-position> || <any-args> ] }
    rule expr-position {:i [ static | relative | absolute | fixed ] & <keyw> }

    #= quotes: [<string> <string>]+ | none
    rule decl:sym<quotes> {:i (quotes) ':'  [ <proforma> || <expr=.expr-quotes> || <any-args> ] }
    rule expr-quotes {:i [ [ <string> <string> ]+ | none & <keyw> ] }

    #= richness: <number>
    rule decl:sym<richness> {:i (richness) ':'  [ <proforma> || <expr=.expr-richness> || <any-args> ] }
    rule expr-richness {:i <number> }

    #= right: <length> | <percentage> | auto
    rule decl:sym<right> {:i (right) ':'  [ <proforma> || <expr=.expr-right> || <any-args> ] }
    rule expr-right {:i [ <length> | <percentage> | auto & <keyw> ] }

    #= size: <length>{1,2} | auto | portrait | landscape
    rule decl:sym<size> {:i (size) ':'  [ <proforma> || <expr=.expr-size> || <any-args> ] }
    rule expr-size {:i [ <length>**1..2 | [ auto | portrait | landscape ] & <keyw> ] }

    #= speak-header: once | always
    rule decl:sym<speak-header> {:i (speak\-header) ':'  [ <proforma> || <expr=.expr-speak-header> || <any-args> ] }
    rule expr-speak-header {:i [ once | always ] & <keyw> }

    #= speak-numeral: digits | continuous
    rule decl:sym<speak-numeral> {:i (speak\-numeral) ':'  [ <proforma> || <expr=.expr-speak-numeral> || <any-args> ] }
    rule expr-speak-numeral {:i [ digits | continuous ] & <keyw> }

    #= speak-punctuation: code | none
    rule decl:sym<speak-punctuation> {:i (speak\-punctuation) ':'  [ <proforma> || <expr=.expr-speak-punctuation> || <any-args> ] }
    rule expr-speak-punctuation {:i [ code | none ] & <keyw> }

    #= speak: normal | none | spell-out
    rule decl:sym<speak> {:i (speak) ':'  [ <proforma> || <expr=.expr-speak> || <any-args> ] }
    rule expr-speak {:i [ normal | none | spell\-out ] & <keyw> }

    #= speech-rate: <number> | x-slow | slow | medium | fast | x-fast | faster | slower
    rule decl:sym<speech-rate> {:i (speech\-rate) ':'  [ <proforma> || <expr=.expr-speech-rate> || <any-args> ] }
    rule expr-speech-rate {:i [ <number> | [ x\-slow | slow | medium | fast | x\-fast | faster | slower ] & <keyw> ] }

    #= stress: <number>
    rule decl:sym<stress> {:i (stress) ':'  [ <proforma> || <expr=.expr-stress> || <any-args> ] }
    rule expr-stress {:i <number> }

    #= table-layout: auto | fixed
    rule decl:sym<table-layout> {:i (table\-layout) ':'  [ <proforma> || <expr=.expr-table-layout> || <any-args> ] }
    rule expr-table-layout {:i [ auto | fixed ] & <keyw> }

    #= text-align: left | right | center | justify
    rule decl:sym<text-align> {:i (text\-align) ':'  [ <proforma> || <expr=.expr-text-align> || <any-args> ] }
    rule expr-text-align {:i [ left | right | center | justify ] & <keyw> }

    #= text-decoration: none | [ underline || overline || line-through || blink ]
    rule decl:sym<text-decoration> {:i (text\-decoration) ':'  [ <proforma> || <expr=.expr-text-decoration> || <any-args> ] }
    rule expr-text-decoration {:i [ none & <keyw> | [ [:my @*SEEN; underline & <keyw> <!seen(0)> | overline & <keyw> <!seen(1)> | line\-through & <keyw> <!seen(2)> | blink & <keyw> <!seen(3)> ]+ ] ] }

    #= text-indent: <length> | <percentage>
    rule decl:sym<text-indent> {:i (text\-indent) ':'  [ <proforma> || <expr=.expr-text-indent> || <any-args> ] }
    rule expr-text-indent {:i [ <length> | <percentage> ] }

    #= text-transform: capitalize | uppercase | lowercase | none
    rule decl:sym<text-transform> {:i (text\-transform) ':'  [ <proforma> || <expr=.expr-text-transform> || <any-args> ] }
    rule expr-text-transform {:i [ capitalize | uppercase | lowercase | none ] & <keyw> }

    #= top: <length> | <percentage> | auto
    rule decl:sym<top> {:i (top) ':'  [ <proforma> || <expr=.expr-top> || <any-args> ] }
    rule expr-top {:i [ <length> | <percentage> | auto & <keyw> ] }

    #= unicode-bidi: normal | embed | bidi-override
    rule decl:sym<unicode-bidi> {:i (unicode\-bidi) ':'  [ <proforma> || <expr=.expr-unicode-bidi> || <any-args> ] }
    rule expr-unicode-bidi {:i [ normal | embed | bidi\-override ] & <keyw> }

    #= vertical-align: baseline | sub | super | top | text-top | middle | bottom | text-bottom | <percentage> | <length>
    rule decl:sym<vertical-align> {:i (vertical\-align) ':'  [ <proforma> || <expr=.expr-vertical-align> || <any-args> ] }
    rule expr-vertical-align {:i [ [ baseline | sub | super | top | text\-top | middle | bottom | text\-bottom ] & <keyw> | <percentage> | <length> ] }

    #= visibility: visible | hidden | collapse
    rule decl:sym<visibility> {:i (visibility) ':'  [ <proforma> || <expr=.expr-visibility> || <any-args> ] }
    rule expr-visibility {:i [ visible | hidden | collapse ] & <keyw> }

    #= voice-family: [[<specific-voice> | <generic-voice> ],]* [<specific-voice> | <generic-voice> ]
    rule decl:sym<voice-family> {:i (voice\-family) ':'  [ <proforma> || <expr=.expr-voice-family> || <any-args> ] }
    rule expr-voice-family {:i [ [ [ <specific-voice> | <generic-voice> ] ] ',' ]* [ [ <specific-voice> | <generic-voice> ] ] }

    #= volume: <number> | <percentage> | silent | x-soft | soft | medium | loud | x-loud
    rule decl:sym<volume> {:i (volume) ':'  [ <proforma> || <expr=.expr-volume> || <any-args> ] }
    rule expr-volume {:i [ <number> | <percentage> | [ silent | x\-soft | soft | medium | loud | x\-loud ] & <keyw> ] }

    #= white-space: normal | pre | nowrap | pre-wrap | pre-line
    rule decl:sym<white-space> {:i (white\-space) ':'  [ <proforma> || <expr=.expr-white-space> || <any-args> ] }
    rule expr-white-space {:i [ normal | pre | nowrap | pre\-wrap | pre\-line ] & <keyw> }

    #= widows: <integer>
    rule decl:sym<widows> {:i (widows) ':'  [ <proforma> || <expr=.expr-widows> || <any-args> ] }
    rule expr-widows {:i <integer> }

    #= width: <length> | <percentage> | auto
    rule decl:sym<width> {:i (width) ':'  [ <proforma> || <expr=.expr-width> || <any-args> ] }
    rule expr-width {:i [ <length> | <percentage> | auto & <keyw> ] }

    #= word-spacing: normal | <length>
    rule decl:sym<word-spacing> {:i (word\-spacing) ':'  [ <proforma> || <expr=.expr-word-spacing> || <any-args> ] }
    rule expr-word-spacing {:i [ normal & <keyw> | <length> ] }

    #= z-index: auto | <integer>
    rule decl:sym<z-index> {:i (z\-index) ':'  [ <proforma> || <expr=.expr-z-index> || <any-args> ] }
    rule expr-z-index {:i [ auto & <keyw> | <integer> ] }
}
