use v6;
#  -- DO NOT EDIT --
# generated by gen-properties.pl --role=CSS::Language::CSS21::Spec::Interface etc/css21-properties.txt
role CSS::Language::CSS21::Spec::Interface {
    method absolute-size($/) { ... }
    method angle($/) { ... }
    method counter($/) { ... }
    method counters($/) { ... }
    method expr-background-attachment($/) { ... }
    method expr-background-color($/) { ... }
    method expr-background-image($/) { ... }
    method expr-background-position($/) { ... }
    method expr-background-repeat($/) { ... }
    method expr-border-color($/) { ... }
    method expr-border-width($/) { ... }
    method expr-cue-after($/) { ... }
    method expr-cue-before($/) { ... }
    method expr-font-family($/) { ... }
    method expr-font-size($/) { ... }
    method expr-font-style($/) { ... }
    method expr-font-variant($/) { ... }
    method expr-font-weight($/) { ... }
    method expr-line-height($/) { ... }
    method expr-list-style-image($/) { ... }
    method expr-list-style-position($/) { ... }
    method expr-list-style-type($/) { ... }
    method expr-outline-color($/) { ... }
    method expr-outline-style($/) { ... }
    method expr-outline-width($/) { ... }
    method family-name($/) { ... }
    method frequency($/) { ... }
    method generic-family($/) { ... }
    method generic-voice($/) { ... }
    method identifier($/) { ... }
    method integer($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method shape($/) { ... }
    method specific-voice($/) { ... }
    method string($/) { ... }
    method time($/) { ... }
    method uri($/) { ... }
}
